# Generated by Django 5.0.14 on 2026-05-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trinee',
            new_name='Trainee',
        ),
    ]
