# Generated by Django 5.0.14 on 2026-05-10 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('trainees', '0002_rename_trinee_trainee'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='courses', to='courses.course'),
            preserve_default=False,
        ),
    ]
