# Generated by Django 5.0.14 on 2026-05-10 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('trainees', '0004_alter_trainee_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='courses', to='courses.course'),
        ),
    ]
