# Generated by Django 5.0.14 on 2026-05-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0005_trainee_is_active_alter_trainee_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trainees'),
        ),
    ]
